foursquare_id: "2AWIT5PBYOXL3TMHNROXT4YAZVDVMOXTCBAROKC5JGDAZEHS"
foursquare_secret: "WF0QKRTYQXYJ0KTYPKEGFOL0CGM5VMUAZHS20EUMQH4HE053"
clarifai_id: "aVk2fAN1tjODqanpnQowmSCq-yI-k5oU_B68NjMY"
clarifai_secret: "3nvsnSoE32gQe0yPZMnIh71xW7oRtUkX4nCU8OtT"
